### ISSUE TITLE
Incorrect contract executed after document signed

### ISSUE THREAD

**Issue by thinwhiteduke80** [openlawteam/openlaw-issue-tracker#13] opened 2018-08-03 11:46 UTC
Hi,

I created sample test contract document ("Employment Contract v3") which I configured to trigger transaction on my contract having address 0xcF09684776A2A440fc51c32320e62107f257ec53. Unfortunately I can see that the system sends transactions to the 0xe532d1d1147ab40d0a245283f4457c733b5e3d41 contract.

I'm not sure if I did anything incorrectly or is this feature still under development.

Best regards.

**Comment by outkaj** [comment] 2018-08-03 16:22
Thanks for reporting this @mislocin!

We will soon be releasing a new version of the application that may fix this issue. I will let you know when that change occurs!

**Comment by jdville03** [comment] 2018-08-06 20:11
Hi @mislocin - Do you mind checking if you're still having the issue of the wrong smart contract being called? I just tested out your sample template "Employment Contract v3" and it looks like the transactions are going to the correct address now.

**Comment by thinwhiteduke80** [comment] 2018-08-07 08:08
Hi @Jdville03 - I just checked this but it seems like it still calls incorrect contract. Please check my "Employment Contract v5". I configured it to trigger contract 0xf7e66ce26C447D398621FE079e8176876bee0a50 but as far as I can see, it still executes contract 0xe532d1d1147ab40d0a245283f4457C733b5E3D41 (for example transaction https://rinkeby.etherscan.io/tx/0xcf700f773d600e330a846c1a1790cd1f7c1f3433947b5caffb76acf4c888f129)

**Comment by jdville03** [comment] 2018-08-08 00:19
@mislocin - I didn't see "Employment Contract v5" saved on openlaw.io. But I tested with "Employment Contract v4" and "Employment Contract v3" and was able to get those working correctly. Can you check one of those again and let us know if it correctly calls contract 0xf7e66ce26C447D398621FE079e8176876bee0a50?

I'm trying to isolate the issue and think it may be related to the saving of a template. When you created the new Employment Contract template that you reported the bug about, did you first start with a source that included the contract address of 0xe532d1d1147ab40d0a245283f4457C733b5E3D41? And then did you save the template after changing the address in the code block to 0xf7e66ce26C447D398621FE079e8176876bee0a50?

**Comment by thinwhiteduke80** [comment] 2018-08-08 09:46
@Jdville03 - indeed, I was creating new contract based on existing one instead of creating new one from scratch. 

After I created new contract now, I can see my correct contract is called as expected.

Unfortunately, it looks like the contract is not called correctly because it does not generate expected outcome.

The code snipped in my OpenLaw.io contract to call the smart contract looks like this:

`
<% #Smart Contract to Pay Employee

[[Pay Vendor:EthereumCall(
contract:Ethereum Contract Address;
interface:[{"name":"withdraw", "type":"function","inputs": [{"name":"target", "type":"address"},{"type":"uint","name":"amount"}],"outputs": []}];
function:"withdraw";
arguments:Recipient Ethereum Address,Payment in Wei;
startDate:Payment Start Date;
endDate:Payment End Date;
repeatEvery:"1 minute")]]
%>
`

(see Employment Contract v7 for details)

The smart contract code looks like this:

`
pragma solidity ^0.4.22;

contract EmploymentContract {
    
    address owner;
    
    event Withdrawal(string status, address indexed to, uint amount);
    
    event WithdrawalFinished(string status);
    
    function withdraw(address target, uint amount) public {
        emit Withdrawal("starting ...", target, amount);
        target.transfer(amount);
        emit WithdrawalFinished("done!");
    }

    function () external payable {}
}
`

So as you can see, the smart contract should send amount of wei to target account both specified as function parameters.

The contract address is: 0x1bA51938D3C329ea862eB7c2d323328923d17117
The target account address is: 0xcfe998bF0f4d27841da548AE9384A16993bCEFD3 (it has positive balance of ether as you can see: https://rinkeby.etherscan.io/address/0x1ba51938d3c329ea862eb7c2d323328923d17117)

When I call my contract "withdraw" function from another tool (Remix) with parameters:
- amount: 100
- target: 0xcfe998bF0f4d27841da548AE9384A16993bCEFD3
- value: 0

I can see 100 wei was transferred from the contract to 0xcfe998bF0f4d27841da548AE9384A16993bCEFD3 target account.

When OpenLaw executes my contract using snipped presented above - I see no effect. I mean - I see that contract is triggered, however I suspect something is wrong with how it is called. Perhaps snipped which I used to embed this contract into OpenLaw.io is incorrect (I found only one example and tried to adapt it) therefore it is called in an incorrect way. Unfortunately I see no way how to debug this so I would appreciate it you could have a look at this.

BTW - is your code open source (I don't think so), perhaps I could look at how it executes the contract myself.

**Comment by jdville03** [comment] 2018-08-08 22:39
Hi @mislocin - thanks for all the info. That's really helpful. And glad to hear that you were able to get the correct contract called. For your new issue, try putting in the full ABI for the `interface` line of your call. I was able to get it to work properly doing that in Employment Contract - Test v7. (btw I sent your contract 1 ether to cover the little amount I withdrew). Our code is not available yet but we do plan on open sourcing in the future.

**Comment by thinwhiteduke80** [comment] 2018-08-09 21:57
Unfortunately, when I enter generated ABI code:

`
[{"constant":false,"inputs":[{"name":"employeeAccountAddress","type":"address"},{"name":"salaryAmount","type":"uint256"}],"name":"paySalaryToEmployee","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"}]
`

I cannot anymore send contract for signing - I get error: red bar, without any description and I can see error 500 at API level

See screenshot:

<img width="661" alt="screen shot 2018-08-09 at 23 55 46" src="https://user-images.githubusercontent.com/298161/43928095-fc820bb0-9c2f-11e8-94e4-dd2ff4f99a78.png">

My contract code:

`
pragma solidity ^0.4.22;

contract EmploymentContract {
    
    function paySalaryToEmployee(address employeeAccountAddress, uint salaryAmount) public {
        employeeAccountAddress.transfer(salaryAmount);
    }

    function () external payable {}
}
`

**Comment by jdville03** [comment] 2018-08-09 22:24
@mislocin - looks like you're now working with a different template and smart contract. Were you able to get the previous one working after putting in the full ABI? This signing error looks like a different issue. If you can let me know which template you're using and what the new smart contract address for this example I'll see if I can reproduce.

**Comment by thinwhiteduke80** [comment] 2018-08-09 22:32
Indeed, I changed the contract but only names of variables / functions to make it more "user friendly". 

New OpenLaw contract is called "EmpTest v3".

My smart contract is deployed under 0xf60b63a2Cd2C49280373aF1C659dFB1B2b3e94dA (source code above).

I have not tried this again with old version of the contract but I think it would fail same way since I have only changed variable names/functions without changing any business logic.

**Comment by jdville03** [comment] 2018-08-09 23:27
thanks @mislocin. I fixed line 18 in your template and should be working now. You just needed to update the name of the function since that changed in your new smart contract. We have an open ticket about improving the error handling that you pointed out. Thanks for that. I'll go ahead and close this issue.

**Closed as completed by jdville03** 2018-08-09 23:27 UTC
Labels: bug
