### ISSUE TITLE
Can't sign a document

### ISSUE THREAD

**Issue by redbeard-26** [openlawteam/openlaw-issue-tracker#1] opened 2018-03-16 21:23 UTC
I created a template (pro bono patent engagement letter) and created a test example and send it to myself for signature. When I attempted to sign it I got the following error:

There was an error when signing the document. <!DOCTYPE html> <html> <head> <title>OpenLaw - A Free Legal Repository</title> <link rel="stylesheet" media="screen" href="/assets/stylesheets/openlaw.css"> <link rel="stylesheet" media="screen" href="/assets/stylesheets/bulma/css/bulma.css"> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> <link rel="shortcut icon" type="image/png" href="/assets/images/favicon.png"> <script src="/assets/javascripts/jquery.min.js" type="text/javascript"></script> <script src="/assets/javascripts/jquery.ui.js" type="text/javascript"></script> <script src="/assets/javascripts/verbal.js" type="text/javascript"></script> <script src="/assets/javascripts/site.js" type="text/javascript"></script> <script src="/assets/javascripts/material.min.js"></script> </head> <body class="index error-page"> <section class="hero"> <div class="hero-body index-hero"> <div class="container"> <h1 class="title logo"> <span class="logo-left">Open</span>Law </h1> <div class="error-page-message"> <h1>Error</h1> <h2>org.adridadou.ethereum.propeller.exception.EthereumApiException: invalid argument 0: hex string has length 38, want 40 for common.Address</h2> <p>We can't find the page you're looking for.</p> <p><img src="https://media.giphy.com/media/nVTa8D8zJUc2A/giphy.gif"/></p> </div> <div class="error-page-links"> Here are a few links that may be helpful:</br> <p><a href="/">Home</a></p> <p><a href="/learn">Help Center</a></p> </div> </div> </div> </section> </body> </html>

The document status still says: waiting for signature

**Comment by outkaj** [comment] 2018-03-18 21:28
Hi @mcarey26 - thank you for reporting your issue!

A couple follow-up questions for you:
1) Did this error occur on openlaw.io? 
2) Did this error occur on Friday afternoon, or previously?

**Comment by redbeard-26** [comment] 2018-03-19 00:47
Yes, openlaw.io and yes on Friday, I think. Right before I logged the issue.

**Comment by outkaj** [comment] 2018-03-19 02:47
Thanks! I'll take a look tomorrow and see if I can reproduce your issue.

**Comment by outkaj** [comment] 2018-03-20 16:43
Hi @mcarey26, I was able to reproduce your issue. I'll look into the causes a bit more and be in touch.

**Comment by redbeard-26** [comment] 2018-03-20 16:49
Thanks.

**Comment by outkaj** [comment] 2018-03-20 18:15
We've figured out the most likely cause of the error and are working on a fix. I will let you know as soon as it is ready!

Thanks for your patience.

**Comment by outkaj** [comment] 2018-03-26 15:33
@mcarey26 we are still testing out our proposed fix for the error you mentioned. Once the testing is done, we will include it in our next deployment and I will update this issue accordingly. Thanks!

**Comment by redbeard-26** [comment] 2018-03-26 15:34
thanks for the update!

**Comment by outkaj** [comment] 2018-04-09 19:46
you're welcome! we are still working on a fix. thanks!

**Comment by outkaj** [comment] 2018-04-30 20:39
Hi @mcarey26! Hope all is well with you. We've pushed some changes to our website - could you try again and see if you still encounter the issue? Thanks very much!

**Comment by redbeard-26** [comment] 2018-04-30 21:05
Great! I'll check it out.

**Comment by outkaj** [comment] 2018-05-21 14:01
hey! do you still encounter the issue after testing @mcarey26 ?

**Comment by redbeard-26** [comment] 2018-05-21 14:56
Thanks for checking. It works now without any issues.

**Comment by outkaj** [comment] 2018-05-21 15:23
great! closing

**Closed as completed by outkaj** 2018-05-21 15:23 UTC
Labels: bug, reproduce
